// Jenkinsfile - Part 1: Basic Structure

pipeline {

    agent any

    // 'stages' is a mandatory block that contains one or more 'stage' blocks.
    stages {
       
        stage('build'){
            steps{
                echo 'Starting the build process...'
                sh 'echo "Simulating application compilation..."'
            }
        }

        stage('Test'){
            steps{
                echo 'Running automated tests...'
                sh 'echo "Running unit and integration tests..."'
            }
        }

        stage('deploy'){
            steps{
                echo 'Initiating deployment...'
                sh 'echo "Deploying to development environment..."'
            }
        }
      
    }
}